import type { Abi } from 'viem';
import artifact from '../../contracts/build/AnkerNote.json';

/**
 * Compiled ABI, asserted to viem's `Abi`.
 *
 * A JSON import widens every string to `string`, so viem and wagmi cannot infer
 * function names or argument types from it. The assertion is safe because the
 * file is generated by solc from contracts/AnkerNote.sol on every
 * `npm run contract:build` — it is not hand-written.
 */
export const ANKER_NOTE_ABI = artifact.abi as Abi;

/**
 * Deployed AnkerNote address.
 *
 * Not a literal in source: filled by `npm run contract:deploy`, which writes
 * contracts/deployments/testnet.json and prints the env line. Undefined until
 * then, and the portfolio says so rather than silently reading address zero.
 */
export const ANKER_NOTE_ADDRESS = (process.env.NEXT_PUBLIC_ANKER_NOTE_ADDRESS ?? '') as `0x${string}` | '';

export const isNoteContractConfigured = () => /^0x[0-9a-fA-F]{40}$/.test(ANKER_NOTE_ADDRESS);
